-- =====================================================================
-- ATELIER GALLERY — seed data
-- Artist: Elena Voss · painter & ceramicist · Atelier Voss, Paris
-- Image paths reference `public/images/...` (generated by scripts/generate-images.mjs).
-- To serve from Supabase Storage instead, upload the files and replace the
-- paths with your public storage URLs.
-- =====================================================================

-- ---------------- categories ----------------
insert into public.categories (name, slug, description) values
  ('Paintings',   'paintings',   'Original oil and mixed-media paintings on linen and panel.'),
  ('Ceramics',    'ceramics',    'Hand-thrown stoneware vessels, bowls and sculptural forms.'),
  ('Sculpture',   'sculpture',   'Carved wood, bronze and assembled sculptural pieces.'),
  ('Textile Art', 'textile-art', 'Hand-woven tapestries and embroidered wall pieces.'),
  ('Home Décor',  'home-decor',  'Functional handmade objects for considered interiors.')
on conflict (slug) do nothing;

-- ---------------- collections ----------------
insert into public.collections (name, slug, description, cover_image, featured, sort_order) values
  ('Terra Memoria',
   'terra-memoria',
   'Earth pigments, raw linen and fired clay — a meditation on soil, memory and the quiet labour of the hand.',
   '/images/artworks/ceramic-1.jpg', true, 1),
  ('Quiet Hours',
   'quiet-hours',
   'Muted interiors and still vessels painted at dawn. Works about slowness, held breath and morning light.',
   '/images/artworks/painting-1.jpg', true, 2),
  ('Woven Light',
   'woven-light',
   'Hand-loomed textiles in undyed wool and plant-dyed thread — rhythm made visible, thread by thread.',
   '/images/artworks/textile-1.jpg', false, 3)
on conflict (slug) do nothing;

-- ---------------- artworks ----------------
-- helper: we resolve category/collection ids inline below.

insert into public.artworks
  (slug, title, description, story, category_id, collection_id, price_cents, edition_type, edition_total, edition_available, stock, status, materials, dimensions, weight_grams, year, featured, published)
values
  ('morning-vessel-i',
   'Morning Vessel I',
   'Hand-thrown stoneware vessel in warm ivory with an iron-oxide wash, wood-fired for three days.',
   'This vessel was thrown at dawn in early spring, when the studio was still cold and the clay fought back. I kept the throwing rings visible — I like the honesty of them. It survived the wood kiln with a single iron kiss down one shoulder, and I decided that mark was the whole point.',
   (select id from public.categories where slug = 'ceramics'),
   (select id from public.collections where slug = 'terra-memoria'),
   48000, 'one_of_one', null, null, 1, 'available',
   array['Stoneware', 'Iron oxide wash', 'Wood-fired'],
   '{"width": 18, "height": 27, "unit": "cm"}'::jsonb, 1450, 2025, true, true),

  ('field-study-no-4',
   'Field Study No. 4',
   'Oil and earth pigment on linen — a low horizon of ochre and umber beneath a pale, weathered sky.',
   'Painted from sketches made walking the same field for eleven mornings. Each day the light was different and the field was the same. I stopped trying to paint what I saw and started painting the repetition instead.',
   (select id from public.categories where slug = 'paintings'),
   (select id from public.collections where slug = 'quiet-hours'),
   240000, 'one_of_one', null, null, 1, 'available',
   array['Oil on linen', 'Earth pigments', 'Beeswax finish'],
   '{"width": 90, "height": 70, "unit": "cm"}'::jsonb, 2800, 2024, true, true),

  ('harvest-bowls-set',
   'Harvest Bowls, Set of Three',
   'A trio of nested stoneware bowls in graduated sizes, glazed inside with a soft oat-milk matte.',
   'I make these in batches of twelve and keep the three that sit best together. They are meant to be used — for morning porridge, for olives at dusk, for keys by the door. The glaze will craze gently with years of washing; that is by design.',
   (select id from public.categories where slug = 'ceramics'),
   (select id from public.collections where slug = 'terra-memoria'),
   18500, 'open', null, null, 8, 'available',
   array['Stoneware', 'Matte food-safe glaze'],
   '{"width": 16, "height": 8, "unit": "cm"}'::jsonb, 900, 2025, true, true),

  ('still-life-with-figs',
   'Still Life with Figs',
   'Oil on panel — figs, a linen cloth and late-afternoon light, painted in a single sustained session.',
   'Figs only hold their pose for a day. I painted this in one long sitting, racing the fruit, and you can feel the hurry in the background and the calm in the cloth. It is my favourite kind of contradiction.',
   (select id from public.categories where slug = 'paintings'),
   (select id from public.collections where slug = 'quiet-hours'),
   165000, 'one_of_one', null, null, 1, 'available',
   array['Oil on wood panel', 'Cold-wax medium'],
   '{"width": 60, "height": 50, "unit": "cm"}'::jsonb, 1900, 2023, false, true),

  ('loom-study-dusk',
   'Loom Study: Dusk',
   'Hand-woven wall tapestry in undyed wool, walnut-dyed thread and raw linen warp.',
   'Woven over six weeks, two hours each evening after the studio closed. The palette follows the light outside my window as autumn came on — I dyed the weft to match the sky on the days I worked. It is, quietly, a calendar.',
   (select id from public.categories where slug = 'textile-art'),
   (select id from public.collections where slug = 'woven-light'),
   89000, 'one_of_one', null, null, 1, 'available',
   array['Undyed wool', 'Walnut-dyed thread', 'Linen warp', 'Oak dowel'],
   '{"width": 75, "height": 110, "unit": "cm"}'::jsonb, 1200, 2024, true, true),

  ('ember-cups-pair',
   'Ember Cups, Pair',
   'Two hand-built ceramic cups with a smoked terracotta exterior and glazed interior.',
   'Pinched rather than thrown, so each keeps the memory of fingers. I smoke-fire them in a small pit behind the studio — the colour is never the same twice, which is why they are sold as pairs from the same firing.',
   (select id from public.categories where slug = 'ceramics'),
   (select id from public.collections where slug = 'terra-memoria'),
   9500, 'limited', 40, 23, 23, 'available',
   array['Stoneware', 'Pit-fired', 'Food-safe liner glaze'],
   '{"width": 9, "height": 10, "unit": "cm"}'::jsonb, 420, 2025, false, true),

  ('standing-figure-ash',
   'Standing Figure (Ash)',
   'Carved ash-wood figure, oil-finished, standing 64 cm tall on a charred oak base.',
   'Carved over winter from a single ash log felled in the studio garden. I worked with the grain and the knots rather than against them — the figure leans the way the tree leaned. The base is the same wood, charred in the Japanese shou-sugi-ban manner.',
   (select id from public.categories where slug = 'sculpture'),
   null,
   320000, 'one_of_one', null, null, 1, 'available',
   array['Carved ash wood', 'Charred oak base', 'Hardwax oil'],
   '{"width": 22, "height": 64, "depth": 20, "unit": "cm"}'::jsonb, 8400, 2023, true, true),

  ('linen-light-i',
   'Linen Light I',
   'Embroidered linen panel — hand-stitched lines mapping a week of morning light across the studio wall.',
   'For one week I marked, each morning, where the light fell on the studio wall, then stitched the marks in flax thread. A drawing made of attention more than image.',
   (select id from public.categories where slug = 'textile-art'),
   (select id from public.collections where slug = 'woven-light'),
   54000, 'one_of_one', null, null, 1, 'reserved',
   array['Belgian linen', 'Hand-dyed flax thread', 'Oak frame'],
   '{"width": 55, "height": 70, "unit": "cm"}'::jsonb, 800, 2024, false, true),

  ('tide-pools-triptych',
   'Tide Pools (Triptych)',
   'Three small oil studies on panel — rock pools at low tide, painted en plein air on the Brittany coast.',
   'Painted with the panels balanced on my knees and the tide coming in. Salt got into the paint; I consider it a collaboration.',
   (select id from public.categories where slug = 'paintings'),
   (select id from public.collections where slug = 'quiet-hours'),
   72000, 'one_of_one', null, null, 1, 'available',
   array['Oil on wood panel (3)'],
   '{"width": 120, "height": 30, "unit": "cm"}'::jsonb, 2400, 2022, false, true),

  ('garden-lantern',
   'Garden Lantern',
   'Pierced stoneware lantern — candlelight escapes through hand-cut apertures in a rough clay body.',
   'Designed for long evenings. The apertures are cut freehand so no two cast the same pattern. Unglazed outside; it weathers beautifully and grows more itself with rain.',
   (select id from public.categories where slug = 'home-decor'),
   (select id from public.collections where slug = 'terra-memoria'),
   13200, 'open', null, null, 12, 'available',
   array['Stoneware', 'Unglazed exterior'],
   '{"width": 14, "height": 22, "unit": "cm"}'::jsonb, 1100, 2025, false, true),

  ('bronze-seed-ii',
   'Bronze Seed II',
   'Cast bronze seed form on a limestone plinth — the second in an edition of twelve.',
   'Modelled in wax from a horse-chestnut seed, then cast in bronze and given a warm brown patina. Small enough to hold; heavy enough to mean it.',
   (select id from public.categories where slug = 'sculpture'),
   null,
   145000, 'limited', 12, 5, 5, 'available',
   array['Cast bronze', 'Limestone plinth'],
   '{"width": 10, "height": 16, "depth": 10, "unit": "cm"}'::jsonb, 2300, 2024, false, true),

  ('winter-table-runner',
   'Winter Table Runner',
   'Hand-loomed runner in undyed wool with a single terracotta stripe — woven on a countermarch loom.',
   'My one concession to the purely functional. Woven slowly, hemmed by hand, and soft enough that people always touch it first and ask second.',
   (select id from public.categories where slug = 'home-decor'),
   (select id from public.collections where slug = 'woven-light'),
   7800, 'open', null, null, 20, 'available',
   array['Undyed wool', 'Madder-dyed stripe'],
   '{"width": 40, "height": 220, "unit": "cm"}'::jsonb, 600, 2025, false, true);

-- ---------------- artwork images ----------------
insert into public.artwork_images (artwork_id, url, alt, position, is_primary)
select a.id, '/images/artworks/' || m.file, m.alt, m.pos, m.pos = 1
from public.artworks a
join (values
  ('morning-vessel-i',      'ceramic-1.jpg',  'Hand-thrown stoneware vessel in ivory with iron wash', 1),
  ('morning-vessel-i',      'ceramic-2.jpg',  'Detail of the iron-oxide shoulder mark', 2),
  ('field-study-no-4',      'painting-1.jpg', 'Oil painting of a low ochre horizon under a pale sky', 1),
  ('field-study-no-4',      'painting-2.jpg', 'Detail of impasto sky in Field Study No. 4', 2),
  ('harvest-bowls-set',     'ceramic-3.jpg',  'Three nested stoneware bowls in graduated sizes', 1),
  ('still-life-with-figs',  'painting-3.jpg', 'Oil still life of figs on a linen cloth', 1),
  ('loom-study-dusk',       'textile-1.jpg',  'Hand-woven tapestry in undyed wool and walnut tones', 1),
  ('loom-study-dusk',       'textile-2.jpg',  'Detail of the hand-woven weft in Loom Study: Dusk', 2),
  ('ember-cups-pair',       'ceramic-2.jpg',  'Pair of smoked terracotta cups', 1),
  ('standing-figure-ash',   'sculpture-1.jpg','Carved ash-wood standing figure on charred oak base', 1),
  ('linen-light-i',         'textile-2.jpg',  'Embroidered linen panel mapping morning light', 1),
  ('tide-pools-triptych',   'painting-4.jpg', 'Triptych of tidal rock pools in oil on panel', 1),
  ('garden-lantern',        'decor-1.jpg',    'Pierced stoneware lantern glowing with candlelight', 1),
  ('bronze-seed-ii',        'sculpture-2.jpg','Cast bronze seed form on limestone plinth', 1),
  ('winter-table-runner',   'textile-1.jpg',  'Hand-loomed wool table runner with terracotta stripe', 1)
) as m(slug, file, alt, pos) on m.slug = a.slug;

-- ---------------- journal posts ----------------
insert into public.journal_posts (slug, title, excerpt, content, cover_image, published, published_at, tags) values
  ('firing-the-wood-kiln',
   'Three Days at the Wood Kiln',
   'Stoking a wood kiln is a conversation in fire. Notes from the spring firing that produced the Terra Memoria vessels.',
   'The kiln takes three days and roughly a cord of oak. You feed it every twenty minutes, day and night, and in return it decides — largely on its own — what your pots will look like.

This spring''s firing was kind. The ivory vessels came out with exactly the iron kiss I''d hoped for on the shoulders, and only two pieces were lost to the fire''s opinion.

People ask why I don''t use an electric kiln. The answer is simple: the wood kiln is a collaborator. I make the form; the fire makes the surface. Half the beauty in the Terra Memoria collection belongs to three days of smoke and patience.',
   '/images/journal/journal-1.jpg', true, '2025-04-18T09:00:00Z',
   array['process', 'ceramics', 'kiln']),

  ('eleven-mornings-one-field',
   'Eleven Mornings, One Field',
   'On repetition as a painting method — the sketches behind Field Study No. 4.',
   'For eleven mornings I walked to the same field with the same sketchbook and stood in the same place.

Nothing about the field changed. Everything about the light did. By the fourth morning I stopped drawing the field at all and started drawing the difference between one morning and the next.

Field Study No. 4 is the painting that came out of those sketches. It isn''t a landscape so much as a record of looking — eleven mornings compressed into one low horizon.',
   '/images/journal/journal-2.jpg', true, '2024-11-02T09:00:00Z',
   array['painting', 'process', 'sketchbook']),

  ('dyeing-with-walnuts',
   'Dyeing with Walnuts',
   'The autumn dye pots behind Loom Study: Dusk, and why I match thread to sky.',
   'Black walnut husks, gathered in October, simmered for an afternoon, strained through linen. The dye bath smells like rain and gives wool the exact colour of wet bark.

For Loom Study: Dusk I dyed the weft to match the sky outside the studio on the evenings I wove. Some rows are the pale grey of early dusk; some are the deep umber of late. The tapestry is, without quite meaning to be, a calendar of one autumn.',
   '/images/journal/journal-3.jpg', true, '2024-10-14T09:00:00Z',
   array['textile', 'natural dye', 'process']),

  ('packing-a-painting',
   'How I Pack a Painting',
   'What happens between "sold" and the doorbell — the unglamorous craft of getting art across the world intact.',
   'Every painting leaves the studio in a double-walled crate I build myself, floated on foam and wrapped in glassine. Corners get extra armour; the crate gets a tilt indicator and a note that says, honestly, "please carry, don''t roll."

It takes about two hours per painting. Collectors sometimes ask why shipping costs what it does — this is why. The work survives the journey because the packing is as considered as the painting.',
   '/images/journal/journal-4.jpg', true, '2025-01-20T09:00:00Z',
   array['studio notes', 'shipping']);

-- ---------------- testimonials ----------------
insert into public.testimonials (name, role, quote, featured, sort_order) values
  ('Margaux Delacroix', 'Collector, Lyon',
   'The vessel arrived packed like a relic and sits in our hallway like it has always lived there. You can feel the hand in it — that is increasingly rare and worth every centime.',
   true, 1),
  ('The Slow Home Review', 'Design editorial',
   'Voss makes objects that slow a room down. Her ceramics carry the quiet confidence of things made without hurry.',
   true, 2),
  ('James Okafor', 'Collector, London',
   'I commissioned a painting for our dining room and the process felt like a correspondence with a friend. The piece itself is the calmest thing we own.',
   true, 3),
  ('Claire Fontaine', 'Interior architect, Paris',
   'Her textiles do something no machine-made piece can: they hold light differently through the day. I specify her work whenever a project needs soul.',
   false, 4);
